Vagrant.configure("2") do |config|
  config.vm.box = "amzn-linux-2017.03"
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.network "forwarded_port", guest: 6379, host: 16379
end
